import os
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from qdrant_client import QdrantClient
from langchain_core.messages import HumanMessage, AIMessage
from src.rag.agent.orchestrator import PolyRAGAgent
from src.rag.agent.llm_config import LLMconfig
from dotenv import load_dotenv
load_dotenv()

app = FastAPI(title="PoliRAG Agent")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"]
)

qdrant_client = QdrantClient(url=os.environ.get("QDRANT_URL"), api_key=os.environ.get("QDRANT_API_KEY"))

llm_config = LLMconfig()

agent_system = PolyRAGAgent(
    qdrant_client=qdrant_client,
    collection_name="uni_docs",
    hf_token=os.environ.get("HF_API_TOKEN"),
    llm_config=llm_config
)

# ---------------------------------------------------------------------------
# UPDATED DATA SCHEMAS FOR MULTI-TURN PERSISTENCE
# ---------------------------------------------------------------------------
class AgentChatPayload(BaseModel):
    thread_id: str                  # Core session identifier key for checkpoint lookups
    message: str                     # Only the latest raw string prompt needed
    course_filter: str = None
    degree_filter: str = None

@app.post("/v1/agent/chat")
async def execute_agent_loop(payload: AgentChatPayload):
    try:
        # Pass the unique thread session inside your LangGraph configuration dictionary
        config = {"configurable": {"thread_id": payload.thread_id}}
        
        # Build the initial inputs
        initial_input = {
            "messages": [HumanMessage(content=payload.message)],
            "course_filter": payload.course_filter,
            "degree_filter": payload.degree_filter
        }
        
        # Fire graph execution. LangGraph automatically fetches past STM/LTM for this thread_id
        output_state = agent_system.agent_app.invoke(initial_input, config=config)
        
        # Get the latest message generated by the LLM inside the graph execution loop
        final_answer = output_state["messages"][-1].content
        
        return {
            "answer": final_answer,
            "citations": output_state.get("citations", []),
            "ltm_summary_status": "Active" if output_state.get("ltm_summary") else "None",
            "query_used": output_state.get("transformed_query", payload.message)
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))